server:
  port: 80
  servlet.session.timeout: 60000
  servlet.context-path: /mybank

logging:
  level:
    root: warn
    com.yc: info
    org.springframework: warn
  file:
    path: ./logs
    name: yc_mybank.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testBank
    username: root
    password: 232328
swagger:
  enabled: true